server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver       # mysql驱动包
    url: jdbc:mysql://localhost:3306/my?useSSL=false&&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    username: root
    password: root123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.lv.entity    # 所有Entity别名类所在包

eureka:
  instance:
    instance-id: payment8002 #修改服务名称
    prefer-ip-address: true  #鼠标移动到名称，显示ip地址
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

